"""Regenerate folder_structure.md as a markdown tree of the repo.

Invoked by a Claude Code PostToolUse hook after Write/Edit/MultiEdit/NotebookEdit
so the tree always reflects the current on-disk state.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "folder_structure.md"

EXCLUDE_DIRS = {
    ".git",
    ".next",
    ".turbo",
    ".cache",
    ".idea",
    ".vscode",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    "dist",
    "build",
    "out",
}

EXCLUDE_FILES = {
    ".DS_Store",
    "Thumbs.db",
}


def walk(path: Path, prefix: str = "") -> list[str]:
    try:
        children = list(path.iterdir())
    except PermissionError:
        return []

    entries = sorted(
        [
            e
            for e in children
            if e.name not in EXCLUDE_DIRS and e.name not in EXCLUDE_FILES
        ],
        key=lambda p: (not p.is_dir(), p.name.lower()),
    )

    lines: list[str] = []
    for i, entry in enumerate(entries):
        is_last = i == len(entries) - 1
        connector = "└── " if is_last else "├── "
        suffix = "/" if entry.is_dir() else ""
        lines.append(f"{prefix}{connector}{entry.name}{suffix}")
        if entry.is_dir():
            extension = "    " if is_last else "│   "
            lines.extend(walk(entry, prefix + extension))
    return lines


def main() -> None:
    body = "\n".join(walk(ROOT))
    content = (
        "# Folder Structure\n"
        "\n"
        "> Auto-generated by `scripts/update_folder_structure.py` via a Claude Code "
        "PostToolUse hook. Do not edit by hand — changes will be overwritten on the next "
        "file modification.\n"
        "\n"
        "```\n"
        f"{ROOT.name}/\n"
        f"{body}\n"
        "```\n"
    )
    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
